-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE SCHEMA IF NOT EXISTS ecommerce;

CREATE TABLE IF NOT EXISTS ecommerce.users
(
    id bigserial NOT NULL,
    id_rol bigint NOT NULL,
    usr character varying(15) NOT NULL,
    passwd character varying(30) NOT NULL,
    name character varying(60) NOT NULL,
    email character varying(60) NOT NULL,
    state boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ecommerce.roles
(
    id bigserial NOT NULL,
    name character varying(45) NOT NULL,
    admin boolean NOT NULL,
    state boolean,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ecommerce.products
(
    id bigserial NOT NULL,
    id_line bigint NOT NULL,
    name character varying(45) NOT NULL,
    description character varying(200) NOT NULL,
    price bigint NOT NULL,
    stock bigint NOT NULL,
    minimum bigint NOT NULL,
    picture character varying(200) NOT NULL,
    state boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ecommerce.wishes
(
    id bigserial NOT NULL,
    id_user bigint NOT NULL,
    id_product bigint NOT NULL,
    state aclitem NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ecommerce.lines
(
    id bigserial NOT NULL,
    name character varying(30) NOT NULL,
    state boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ecommerce.sales
(
    id bigserial NOT NULL,
    id_user bigint NOT NULL,
    id_product bigint NOT NULL,
    quantity bigint NOT NULL,
    date date NOT NULL,
    state boolean NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE ecommerce.users
    ADD FOREIGN KEY (id_rol)
    REFERENCES ecommerce.roles (id)
    NOT VALID;


ALTER TABLE ecommerce.products
    ADD FOREIGN KEY (id_line)
    REFERENCES ecommerce.lines (id)
    NOT VALID;


ALTER TABLE ecommerce.wishes
    ADD FOREIGN KEY (id_user)
    REFERENCES ecommerce.users (id)
    NOT VALID;


ALTER TABLE ecommerce.wishes
    ADD FOREIGN KEY (id_product)
    REFERENCES ecommerce.products (id)
    NOT VALID;


ALTER TABLE ecommerce.sales
    ADD FOREIGN KEY (id_user)
    REFERENCES ecommerce.users (id)
    NOT VALID;


ALTER TABLE ecommerce.sales
    ADD FOREIGN KEY (id_product)
    REFERENCES ecommerce.products (id)
    NOT VALID;

END;